server:
  port: 9999
  
spring:
  application:
    name: zuul-proxy
    
eureka:
  client:
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
      
      
      
zuul: 
  prefix: /app
  routes: 
    test-redirect: 
       path: /redirect/**
       location: http://www.google.com
       
    by-service:  
       path: /services/**
       location: emp-service
       
       
    by-client: 
        path: /client/**
        location: hr-service
        
    by-direct: 
        path: /proxy/**
        location: http://localhost:8081
    